'use client';

import { useState } from 'react';

/** Opens the stored HTML of a logged email in a sandboxed iframe. */
export function EmailPreview({ subject, html }: { subject: string; html: string }) {
  const [open, setOpen] = useState(false);

  return (
    <>
      <button className="btn btn-ghost btn-xs" onClick={() => setOpen(true)} disabled={!html}>
        Preview
      </button>

      {open && (
        <div className="modal-ov open" onClick={(e) => e.target === e.currentTarget && setOpen(false)}>
          <div className="modal-box" style={{ maxWidth: 720 }}>
            <div className="modal-hd">
              <div className="modal-title" style={{ fontSize: 14 }}>{subject}</div>
              <button className="modal-close" onClick={() => setOpen(false)}>✕</button>
            </div>
            <div className="modal-body" style={{ padding: 0 }}>
              <iframe
                title={subject}
                // The stored HTML is generated by our own templates, but the
                // sandbox keeps it inert regardless.
                sandbox=""
                srcDoc={html}
                style={{ width: '100%', height: '65vh', border: 0, background: '#fff' }}
              />
            </div>
          </div>
        </div>
      )}
    </>
  );
}
